
name: 'AppEcrAction'
description: 'Check and create an ecr for microservice'
inputs:
  aws-role:
    description: 'Aws role to apply changes'
    default: ''
  aws-region:
    description: 'Aws region'
    default: 'eu-central-1'
  environment:
    description: 'Finalcad envrionment: production, staging, sandbox'
    default: ''
  registry:
    description: 'Registry name'
    default: ''
  pulling-accounts:
    description: 'Accounts number separated by commas to allow cross account pull'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Deprecated version of FinalCAD/AppEcrAction
      shell: bash
      run: |
        echo '::error title=Deprecated version of FinalCAD/AppEcrAction::This version of FinalCAD/AppEcrAction is deprecated use `v1` instead.'
        exit 1
